Implement logbook in davison util

diff --git a/shell/davison b/shell/davison
--- a/shell/davison
+++ b/shell/davison
@@ -7,15 +7,41 @@ shift
     echo "usage: $(basename $0) command args..."
     echo ""
     echo "Available commands"
+    echo " (NI => not yet implemented/meregd) "
     echo ""
-    echo "    printbefore"
-    echo "    printafter"
-    echo "    printbetween"
-    echo "    extract"
-    echo "    epoch"
-    echo "    lastmonday"
-    echo "    timenow"
-    echo "    nextsunday"
+    echo "    NI printbefore           print a csv with datecolumn 0 before a certain date"
+    echo "    NI printafter            print a csv with datecolumn 0 after a certain date"
+    echo "    NI printbetween          print a csv with datecolumn 0 between dates"
+    echo "    extract               generic archive extractor"
+    echo "    epoch                 convert seconds-since-epoch to readable"
+    echo "    lastmonday            datetime of last monday"
+    echo "    timenow               datetime now"
+    echo "    nextsunday            datetime of next sunday"
+    echo "    catless               either cat or less, depending on terminal size"
+    echo "    mans"
+    echo "    remspace              remove spaces from passed string"
+    echo "    filenameNoExt         get filename without its extension"
+    echo "    running               list running jobs"
+    echo "    uuidrecord            generate and record a uuid"
+    echo "    uuidlast              return the last recorded uuid"
+    echo "    literatureTitle"
+    echo "    myip"
+    echo "    ppath"
+    echo "    moveNamedScreenshot"
+    echo "    noteadd|na"
+    echo "    noteview|nv"
+    echo "    noteclear|nc"
+    echo "    notefile"
+    echo "    headtail|ht"
+    echo "    logbook               Deal with logbook entries.  Subcommands edit|e,view|v,commit|c"
+    echo "    md|markdown"
+    echo "    glog"
+    echo "    gitinit"
+    echo "    eps2pdf"
+    echo "    svg2eps"
+    echo "    ff"
+    echo "    fd"
+    echo "    docker"
     exit
 }
 
@@ -37,7 +63,7 @@ case "$command" in
                 *.zip)       unzip $1       ;;
                 *.Z)         uncompress $1  ;;
                 *.7z)        7z x $1        ;;
-                *)     echo "'$1' cannot be extracted via extract()" ;;
+                *)     echo "'$1' cannot be extracted via $(basename $0) extract" ;;
             esac
         else
             echo "'$1' is not a valid file"
@@ -45,6 +71,7 @@ case "$command" in
     epoch) date -r $1 +"%Y%m%d %H:%M:%S" ;;
     lastmonday) date -v -monday +"%Y-%m-%d"    ;;
     timenow) date +"%Y-%m-%d %H:%M:%S" ;;
+    today) date +"%Y-%m-%d" ;;
     nextsunday) date -v +sunday -v +7d +%F ;;
     catless)
         height=$(tput lines)
@@ -128,11 +155,19 @@ case "$command" in
         fi
         awk -F $delim 'NR == 2 { printf $1; exit }' $1 && echo -n " till "
         tail -n 1 $1 | awk -F $delim '{ print $1 }' ;;
-    logbook)
+    logbook|lb)
         opt="$1"
-        case "$opt" in edit|e) echo "editing todays logbook" ;;
-            view|v) echo "viewing todays logbook" ;;
-            commit|c) echo "commiting todays logbook" ;;
+        logbook_today=$(date +"%Y/%Y-%m-%d--%a.md")
+        lb=$LOGBOOK_DIR$logbook_today
+        case "$opt" in 
+            edit|e) $EDITOR "$lb" ;;
+            view|v) [ -e "$lb" ] && davison catless "$lb" || echo "No logbook entry today" ;;
+            commit|c) 
+                pushd $LOGBOOK_DIR
+                git add $logbook_today
+                git commit -m "Log $(date +%F)" ;;
+            *)
+                echo "usage: $(basename $0) logbook edit|view|commit" ;;
         esac ;;
     md|markdown) 
         opt="$1"
@@ -152,6 +187,8 @@ case "$command" in
                 [ -e $fn ] && rm $fn
                 pandoc -s -c ~/.dotfiles/github-markdown.css --self-contained --mathjax $1 > $fn ;;
             preview) ;;
+            *)
+                echo "usage: $(basename $0) markdown tidy|tidynoref|pdf|html|preview" ;;
         esac ;;
     glog) 
        opt="$1"
@@ -185,5 +222,14 @@ case "$command" in
             ipy|py|python)
                docker run -it --rm -v `pwd`:/home/jovyan/work/ jupyter/tensorflow-notebook start.sh ipython ;;
        esac ;;
+    *) 
+        echo "Unknown command: $command" 
+        echo ""
+        davison
+        ;;
 esac
 exit $?
+
+
+
+
